'use client';
import Link from 'next/link';
import {useEffect,useRef,useState,useMemo} from 'react';
import {Orbit,ArrowUpRight,ArrowDown,ScanLine,Plus,Minus} from 'lucide-react';
import WeatherMap from './weather-map';
import {simulate,scenarios,type Scenario} from '@/lib/weather-engine';
export function Brand(){return <Link href="/" className="brand"><Orbit size={29}/><span>vayu<span className="brand-light">mandal</span><small>WEATHER INTELLIGENCE</small></span></Link>}
const chapters=[{title:'Follow the system.',sub:'01 / SPACE + TIME',body:'A storm is a moving system, not a collection of disconnected pixels. Follow its centroid through the medium-range window to see where the story is heading.',detail:'Explore eight forecast frames',layer:'trajectory'}, {title:'Keep the uncertainty.',sub:'02 / ENSEMBLE EVIDENCE',body:'One line is never the whole forecast. Compare possible outcomes and inspect the distribution before attaching certainty to a location.',detail:'Inspect the illustrative ensemble spread',layer:'ensemble'}, {title:'Bring it down to place.',sub:'03 / LOCAL CONTEXT',body:'Connect the evolving footprint to a location. Carry the coordinates, threshold probability and evidence into a reviewable spatial alert.',detail:'Review a 5 km illustrative alert radius',layer:'intensity'}];
export default function Landing(){
 const root=useRef<HTMLElement>(null),[scenario,setScenario]=useState<Scenario>('cyclone'),[day,setDay]=useState(5),[chapter,setChapter]=useState(0),[open,setOpen]=useState<number|null>(0);
 const sample=useMemo(()=>simulate({scenario,day,members:24,seed:26078}),[scenario,day]);
 useEffect(()=>{const el=root.current;if(!el)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.12});el.querySelectorAll('[data-reveal]').forEach(x=>observer.observe(x));const sections=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setChapter(Number((e.target as HTMLElement).dataset.chapter))}),{rootMargin:'-25% 0px -35% 0px'});el.querySelectorAll('[data-chapter]').forEach(x=>sections.observe(x));let frame=0;const update=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const max=document.documentElement.scrollHeight-innerHeight;el.style.setProperty('--reading',String(max>0?scrollY/max:0));el.style.setProperty('--drift',`${Math.min(scrollY*.12,75)}px`)})};addEventListener('scroll',update,{passive:true});update();return()=>{observer.disconnect();sections.disconnect();removeEventListener('scroll',update);cancelAnimationFrame(frame)}},[]);
 return <main ref={root} className="field-guide"><div className="reading-progress"/><header className="nav shell"><Brand/><nav><a href="#solution">The approach</a><a href="#observatory">Try a scenario</a><a href="#research">Research notes</a></nav><Link href="/dashboard" className="button small">Enter workspace <ArrowUpRight size={16}/></Link></header>
 <section className="editorial-hero shell"><div className="edition-line"><span>FIELD NOTES / 001</span><span>INDIA · 08°–37° N</span><span>SIH 2026 / PS 26078</span></div><div className="hero-statement"><div><div className="eyebrow">AN EARLIER VIEW OF WHAT COMES NEXT</div><h1>Weather moves.<br/>Our understanding<br/>should <em>move with it.</em></h1></div><div className="hero-aside"><span className="folio">↗</span><p>From a shifting weather system to the places in its path. A research workspace for tracking extremes, exploring uncertainty, and making local impact visible.</p><Link href="/dashboard" className="button">Explore the live demo <ArrowUpRight size={18}/></Link><small>Interactive prototype / synthetic data</small></div></div><div className="hero-atlas"><WeatherMap hero day={day} scenario={scenario}/><div className="atlas-caption"><span className="status-dot"/> A SYSTEM IN MOTION <span>DAY {day} / +{day*24} H</span></div><div className="atlas-title">The atmosphere has<br/>no district borders.</div><div className="atlas-scrub"><label htmlFor="hero-day">Trace the trajectory <span>Day {day}</span></label><input id="hero-day" type="range" min="3" max="10" value={day} onChange={e=>setDay(Number(e.target.value))}/><small>DAY 03 <span>DAY 10</span></small></div></div><a className="scroll-invitation" href="#solution"><ArrowDown size={16}/> Scroll to follow the evidence <span>01 — 03</span></a></section>
 <section id="solution" className="story-section shell"><div className="story-intro" data-reveal><span className="eyebrow">THE APPROACH</span><h2>One system.<br/><em>Three scales of understanding.</em></h2><p>The useful question is not only “how extreme?” It is where, when, and how much confidence we should place in the answer.</p></div><div className="story-layout"><div className="story-sticky"><div className="story-map"><WeatherMap hero day={chapter===0?3:chapter===1?6:9} layer={chapters[chapter].layer}/><span className="story-counter">0{chapter+1} / 03</span></div><div className="chapter-switch" aria-label="Explore the approach">{chapters.map((ch,i)=><a key={ch.sub} href={`#chapter-${i}`} aria-current={chapter===i?'step':undefined} onClick={()=>setChapter(i)}><span>0{i+1}</span>{['Track','Evaluate','Locate'][i]}</a>)}</div></div><div className="story-chapters">{chapters.map((ch,i)=><article id={`chapter-${i}`} data-chapter={i} data-reveal key={ch.sub}><span className="eyebrow">{ch.sub}</span><h3>{ch.title}</h3><p>{ch.body}</p><span className="chapter-detail"><ScanLine size={17}/>{ch.detail}</span></article>)}</div></div></section>
 <section className="scenario-section" id="observatory"><div className="shell"><div className="section-heading" data-reveal><div><span className="eyebrow">THE OBSERVATORY / HANDS ON</span><h2>Change the conditions.<br/><em>Read the consequences.</em></h2></div><p>Three synthetic systems. The same connected workflow. Select an event and scrub through the forecast to inspect how the evidence changes.</p></div><div className="scenario-tabs" role="group" aria-label="Preview weather scenario">{(Object.keys(scenarios) as Scenario[]).map((s,i)=><button key={s} aria-pressed={scenario===s} onClick={()=>setScenario(s)}><span>0{i+1}</span>{['Cyclone','Heatwave','Cold wave'][i]}<ArrowUpRight size={18}/></button>)}</div><div className="scenario-experiment"><div className="experiment-map"><WeatherMap day={day} scenario={scenario}/></div><div className="experiment-readout"><span className="eyebrow">SYNTHETIC / 24 MEMBERS</span><h3>{sample.scenario.label}</h3><div className="experiment-value">{Math.round(sample.probability*100)}<span>%</span></div><p>of members {scenario==='coldwave'?'at or below':'at or above'} {sample.scenario.threshold} {sample.scenario.unit}</p><label htmlFor="preview-day">Forecast lead <strong>Day {day}</strong></label><input id="preview-day" type="range" min="3" max="10" value={day} onChange={e=>setDay(Number(e.target.value))}/><div className="preview-range"><span>+72 hours</span><span>+240 hours</span></div><Link className="text-link" href={`/dashboard?scenario=${scenario}&day=${day}`}>Investigate this scenario <ArrowUpRight size={18}/></Link></div></div></div></section>
 <section className="research-section shell" id="research"><div data-reveal><span className="eyebrow">RESEARCH NOTES / OPEN BY DESIGN</span><h2>Ambitious by design.<br/><em>Honest about the evidence.</em></h2><p>Our proposed architecture connects spherical graph learning with conditional diffusion. This build makes the investigation workflow tangible while model training and independent validation remain ahead.</p><Link className="text-link" href="/dashboard?tab=methodology">Read the methodology <ArrowUpRight size={17}/></Link></div><div className="research-accordion">{[['What can I actually use today?','A seeded numerical simulator, reproducible ensembles, centroid trajectories, synthetic grid comparisons, local point inspection and GeoJSON exports. Every visible scenario can be investigated in the workspace.'],['Why connect tracking and downscaling?','Tracking identifies an evolving region of interest. Conditional downscaling is proposed to examine local variability within that region, keeping the investigation attached to the same weather event. No trained GNN or diffusion checkpoint is installed in this build.'],['What does a 5 km output mean?','It describes the target grid or illustrative alert radius, not proven forecast skill. Finer output still needs calibration, independent event holdouts, physical consistency checks and expert review.'],['Who is this being built for?','Forecast researchers and preparedness teams who need to inspect the evidence behind an evolving threat. The prototype supports exploration; official IMD warnings remain the source for real decisions.']].map(([q,a],i)=><article key={q}><button aria-expanded={open===i} aria-controls={`answer-${i}`} onClick={()=>setOpen(open===i?null:i)}><span>0{i+1}</span>{q}{open===i?<Minus size={18}/>:<Plus size={18}/>}</button><div id={`answer-${i}`} hidden={open!==i}><p>{a}</p></div></article>)}</div></section>
 <section className="closing-section shell" data-reveal><span className="eyebrow">FROM THE BIG PICTURE TO A SINGLE PLACE</span><h2>Follow the next<br/><em>question.</em></h2><Link href="/dashboard" className="button">Open the forecast workspace <ArrowUpRight size={20}/></Link><span className="closing-orbit" aria-hidden="true"><Orbit/></span></section><footer className="shell"><Brand/><p>Research prototype · Synthetic scenarios<br/>Ministry of Earth Sciences / NCMRWF problem statement</p><a href="/api/health">API status <ArrowUpRight size={14}/></a></footer></main>
}
