/** Reproducible demonstrator. No trained weights or operational forecast data. */
export type Scenario='cyclone'|'heatwave'|'coldwave';
export type Config={scenario:Scenario;day:number;members:number;seed:number};
export const scenarios={cyclone:{label:'Bay of Bengal cyclone',region:'Bay of Bengal',unit:'km/h',variable:'10 m wind',threshold:90,baseline:25,spread:12},heatwave:{label:'North India heatwave',region:'Northwest India',unit:'°C',variable:'2 m temperature',threshold:42,baseline:32,spread:4},coldwave:{label:'Himalayan cold wave',region:'Northern India',unit:'°C',variable:'2 m temperature',threshold:2,baseline:11,spread:4}};
export function validateConfig(input:Record<string,unknown>):Config{const scenario=input.scenario??'cyclone';if(!Object.hasOwn(scenarios,String(scenario)))throw Error('scenario must be cyclone, heatwave or coldwave');const number=(name:string,def:number,min:number,max:number)=>{const v=input[name]===undefined?def:Number(input[name]);if(!Number.isInteger(v)||v<min||v>max)throw Error(`${name} must be an integer from ${min} to ${max}`);return v};return {scenario:scenario as Scenario,day:number('day',5,3,10),members:number('members',24,8,64),seed:number('seed',26078,1,999999)}}
function random(seed:number){let x=seed>>>0;return ()=>{x+=0x6D2B79F5;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}}
function normal(r:()=>number){return Math.sqrt(-2*Math.log(Math.max(r(),1e-10)))*Math.cos(2*Math.PI*r())}
export function quantile(a:number[],p:number){const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p;return s[Math.floor(i)]+(s[Math.ceil(i)]-s[Math.floor(i)])*(i%1)}
/** Numerical EFI integral: 2/pi integral_0^1 (p-Fforecast(Qclimate(p)))/sqrt(p(1-p)) dp. */
export function efi(forecast:number[],climate:number[]){let sum=0;const sorted=[...climate].sort((a,b)=>a-b);for(let i=0;i<200;i++){const p=(i+.5)/200;const q=sorted[Math.floor(p*(sorted.length-1))];const f=forecast.filter(x=>x<=q).length/forecast.length;sum+=(p-f)/Math.sqrt(p*(1-p))}return Math.max(-1,Math.min(1,2/Math.PI*sum/200))}
export function center(s:Scenario,day:number){const d=day-3;return s==='cyclone'?{lat:15+d*1.1,lon:86+d*.48}:s==='heatwave'?{lat:28+d*.1,lon:75+d*.24}:{lat:33-d*.15,lon:78-d*.2}}
export function haversine(a:{lat:number;lon:number},b:{lat:number;lon:number}){const r=Math.PI/180,dlat=(b.lat-a.lat)*r,dlon=(b.lon-a.lon)*r;return 6371*2*Math.asin(Math.sqrt(Math.sin(dlat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dlon/2)**2))}
export function simulate(config:Config){const {scenario,day,members,seed}=config,s=scenarios[scenario],r=random(seed+day*101+Object.keys(scenarios).indexOf(scenario)*5000);const mean=scenario==='cyclone'?104+20*Math.sin((day-3)/7*Math.PI):scenario==='heatwave'?44+2.5*Math.sin(day):-.5-2*Math.sin(day);const sigma=scenario==='cyclone'?7+day*1.3:1.2+day*.18;const ensemble=Array.from({length:members},()=>mean+normal(r)*sigma).map(v=>scenario==='cyclone'?Math.max(0,v):v);const climate=Array.from({length:600},()=>s.baseline+normal(r)*s.spread);const index=efi(ensemble,climate);const probability=ensemble.filter(v=>scenario==='coldwave'?v<=s.threshold:v>=s.threshold).length/members;const c=center(scenario,day);const severity=probability>=.7?'severe':probability>=.35?'moderate':'low';const tracks=Array.from({length:8},(_,i)=>({...center(scenario,i+3),day:i+3,spreadKm:18+(i+3)*8}));
 const fine=Array.from({length:25},(_,y)=>Array.from({length:25},(_,x)=>{const d2=((x-12)/6)**2+((y-12)/7)**2;const signal=Math.exp(-d2/2);const terrain=Math.sin(x*.9)*Math.cos(y*.7);let v=s.baseline+(mean-s.baseline)*signal+terrain*signal*(scenario==='cyclone'?7:1.3);if(scenario==='cyclone')v=Math.max(0,v);return Number(v.toFixed(2))}));
 const coarse=Array.from({length:10},(_,y)=>Array.from({length:10},(_,x)=>{const ix=Math.floor(x*2.4),iy=Math.floor(y*2.4);let total=0,count=0;for(let j=0;j<3;j++)for(let k=0;k<3;k++){total+=fine[Math.min(24,iy+j)][Math.min(24,ix+k)];count++}return Number((total/count).toFixed(2))}));
 const smooth=fine.map((row,y)=>row.map((_,x)=>{let sum=0,count=0;for(let j=-3;j<=3;j++)for(let k=-3;k<=3;k++){sum+=fine[Math.max(0,Math.min(24,y+j))][Math.max(0,Math.min(24,x+k))];count++}return Number((sum/count).toFixed(2))}));
 const extreme=(grid:number[][])=>scenario==='coldwave'?Math.min(...grid.flat()):Math.max(...grid.flat());
 return {mode:'synthetic' as const,model:'seeded-numerical-demonstrator',config,scenario:s,issuedAt:'2026-09-30T00:00:00Z',validAt:new Date(Date.UTC(2026,8,30+day)).toISOString(),centroid:c,ensemble,efi:Number(index.toFixed(3)),probability,median:quantile(ensemble,.5),p10:quantile(ensemble,.1),p90:quantile(ensemble,.9),severity,tracks,grid:{fine,coarse,smooth,fineResolutionKm:5,coarseResolutionKm:12,fineExtreme:extreme(fine),smoothExtreme:extreme(smooth)},alert:{id:`DEMO-${scenario}-${day}-${seed}-${members}`,event:scenario,severity,probability,centroid:c,radiusKm:5,leadHours:day*24,threshold:s.threshold,unit:s.unit,status:'demonstration',guidance:'Synthetic research output. Consult official IMD warnings for real decisions.'}};
}
export type Forecast=ReturnType<typeof simulate>;
export function alertGeoJSON(f:Forecast){const c=f.centroid,R=6371,delta=5/R,rad=Math.PI/180,lat=c.lat*rad,lon=c.lon*rad;const ring=Array.from({length:65},(_,i)=>{const b=i*2*Math.PI/64;const p=Math.asin(Math.sin(lat)*Math.cos(delta)+Math.cos(lat)*Math.sin(delta)*Math.cos(b));const l=lon+Math.atan2(Math.sin(b)*Math.sin(delta)*Math.cos(lat),Math.cos(delta)-Math.sin(lat)*Math.sin(p));return [l/rad,p/rad]});return {type:'FeatureCollection',features:[{type:'Feature',geometry:{type:'Point',coordinates:[c.lon,c.lat]},properties:{...f.alert,validAt:f.validAt}},{type:'Feature',geometry:{type:'Polygon',coordinates:[ring]},properties:{id:f.alert.id,radiusKm:5,mode:'synthetic',severity:f.severity}}]}}
